### ISSUE TITLE
How to crop the face detected via Camera

### ISSUE THREAD

**Issue by iDroidindia** [jason9075/dlib-android-jni-test#1]
Hi,

Thanks for sharing such a nice project for Facial Recognition. 
I have implemented this project & I am able to detect the faces. But I want that once the face is detected it should be able to crop the image to the facial portion & return it in the image view. How can I do that  ?

**Comment by jason9075** [comment]
You can check this stackoverflow
https://stackoverflow.com/questions/24134014/need-example-of-cropping-an-image-in-android-app
cropping image on android

**Comment by iDroidindia** [comment]
Hi,

Thanks for the response. However, I am still facing issues. How can I crop the Image from the Camera Frame with the face is detected.  
I need to click the picture of the face detected by the Camera Frame with its facial coordinates.  
Two files are attached for reference. Any help would be appreciated.
[Desktop.zip](https://github.com/jason9075/dlib-android-jni-test/files/2723281/Desktop.zip)

**Comment by jason9075** [comment]
Sorry I am too busy to check my project code...
But I think the step is this
1. get bitmap from frame , use this method "getBitmapFromFrame(frame, transform)"
2. get detection bounding box 
3. use bounding box coordinate to crop (https://stackoverflow.com/questions/15789049/crop-a-bitmap-image)

**Comment by iDroidindia** [comment]
Ok, Thanks for the same. I have done it & its working fine now. 
Still I have a confusion, how can I use this in my own project ?
